version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - "80:8080"

  php:
    container_name: php
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
